services:
  php:
    image: thecodingmachine/php:${PHP_VERSION:-8.3}-v4-cli
    container_name: async-console_php
    environment:
      - PHP_EXTENSION_XDEBUG=1
      - XDEBUG_MODE=off
    init: true
    networks:
      - async-console
    restart: "no"
    volumes:
      - ./:/usr/src/app

networks:
  async-console:
    driver: bridge
    name: async-console
